export const FETCH_SERVERS_INITIATED = 'FETCH_SERVERS_INITIATED'

export const FETCH_SERVERS_SUCCESS = 'FETCH_SERVERS_SUCCESS'

export const FETCH_SERVERS_INITIATED_NO_UPDATES_VERSION = 'FETCH_SERVERS_INITIATED_NO_UPDATES_VERSION'

export const FETCH_SERVERS_SUCCESS_NO_UPDATES_VERSION = 'FETCH_SERVERS_SUCCESS_NO_UPDATES_VERSION'

export const RESET_SERVERS_LIST_STATE = 'RESET_SERVERS_LIST_STATE'
