export const FETCH_CITIES_INITIATED = 'FETCH_CITIES_INITIATED'
export const FETCH_CITY_INITIATED = 'FETCH_CITY_INITIATED'
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'

export const FETCH_CITIES_INITIATED_NO_UPDATES_VERSION = 'FETCH_CITIES_INITIATED_NO_UPDATES_VERSION'
export const FETCH_CITIES_SUCCESS_NO_UPDATES_VERSION = 'FETCH_CITIES_SUCCESS_NO_UPDATES_VERSION'

export const SELECT_CHANGE_CITIES_LIST = 'SELECT_CHANGE_CITIES_LIST'
export const PAGE_CHANGE_LIST_CITIES = 'PAGE_CHANGE_LIST_CITIES'
export const RESET_CITIES_FILTERS = 'RESET_CITIES_FILTERS'
