export const FETCH_PROTOCOLS_INITIATED = 'FETCH_PROTOCOLS_INITIATED'
export const FETCH_PROTOCOLS_SUCCESS = 'FETCH_PROTOCOLS_SUCCESS'
export const FETCH_PROTOCOLS_FAILED = 'FETCH_PROTOCOLS_FAILED'

export const FETCH_MAIN_PROTOCOLS_INITIATED = 'FETCH_MAIN_PROTOCOLS_INITIATED'
export const FETCH_MAIN_PROTOCOLS_SUCCESS = 'FETCH_MAIN_PROTOCOLS_SUCCESS'
export const FETCH_MAIN_PROTOCOLS_FAILED = 'FETCH_MAIN_PROTOCOLS_FAILED'
