export const FETCH_TICKETS_INITIATED = 'FETCH_TICKETS_INITIATED'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILED = 'FETCH_TICKETS_FAILED'
export const FETCH_TICKETS_INITIATED_NO_UPDATES_VERSION = 'FETCH_TICKETS_INITIATED_NO_UPDATES_VERSION'
export const FETCH_TICKETS_SUCCESS_NO_UPDATES_VERSION = 'FETCH_TICKETS_SUCCESS_NO_UPDATES_VERSION'
export const RESET_TICKETS_LIST_STATE = 'RESET_TICKETS_LIST_STATE'

export const SELECT_CHANGE_TICKETS_LIST = 'SELECT_CHANGE_TICKETS_LIST'
export const PAGE_CHANGE_LIST_TICKETS = 'PAGE_CHANGE_LIST_TICKETS'
