export const UPDATE_ADMIN_INITIATED = 'UPDATE_ADMIN_INITIATED'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAILED = 'UPDATE_ADMIN_FAILED'
export const RESET_STATE = 'RESET_STATE'
