export const FETCH_SUBSCRIPTIONS_INITIATED = 'FETCH_SUBSCRIPTIONS_INITIATED'
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS'
export const FETCH_SUBSCRIPTIONS_FAILED = 'FETCH_SUBSCRIPTIONS_FAILED'
export const FETCH_SUBSCRIPTIONS_INITIATED_NO_UPDATES_VERSION = 'FETCH_SUBSCRIPTIONS_INITIATED_NO_UPDATES_VERSION'
export const FETCH_SUBSCRIPTIONS_SUCCESS_NO_UPDATES_VERSION = 'FETCH_SUBSCRIPTIONS_SUCCESS_NO_UPDATES_VERSION'
export const RESET_SUBSCRIPTIONS_LIST_STATE = 'RESET_SUBSCRIPTIONS_LIST_STATE'

export const PAGE_CHANGE_LIST_SUBSCRIPTIONS = 'PAGE_CHANGE_LIST_SUBSCRIPTIONS'

export const SELECT_CHANGE_SUBSCRIPTIONS_LIST = 'SELECT_CHANGE_SUBSCRIPTIONS_LIST'

export const DISABLE_SUBSCRIPTION_INITIATED = 'DISABLE_SUBSCRIPTION_INITIATED'

export const DISABLE_SUBSCRIPTION_SUCCESS = 'DISABLE_SUBSCRIPTION_SUCCESS'

export const ENABLE_SUBSCRIPTION_INITIATED = 'ENABLE_SUBSCRIPTION_INITIATED'

export const ENABLE_SUBSCRIPTION_SUCCESS = 'ENABLE_SUBSCRIPTION_SUCCESS'
