export const FETCH_STATS_INITIATED = 'FETCH_STATS_INITIATED'
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS'
export const FETCH_STATS_FAILED = 'FETCH_STATS_FAILED'
export const REST_STATS = 'REST_STATS'