export const FETCH_ADMINS_INITIATED = 'FETCH_ADMINS_INITIATED'
export const FETCH_ADMINS_FAILED = 'FETCH_ADMINS_FAILED'
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS'

export const SELECT_CHANGE = 'SELECT_CHANGE'
export const PAGE_CHANGE = 'PAGE_CHANGE'
export const FETCH_ADMINS_INITIATED_NO_UPDATES_VERSION = 'FETCH_ADMINS_INITIATED_NO_UPDATES_VERSION'
export const FETCH_ADMINS_SUCCESS_NO_UPDATES_VERSION = 'FETCH_ADMINS_SUCCESS_NO_UPDATES_VERSION'
export const RESET_ADMINS_LIST_STATE = 'RESET_ADMINS_LIST_STATE'

export const FETCH_ADMIN_INITIATED = 'FETCH_ADMIN_INITIATED'
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS'
export const FETCH_ADMIN_FAILED = 'FETCH_ADMIN_FAILED'
