export const INITIATE_REGISTRATION = 'REGISTRATION_INITIATED'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const RESET_REGISTER_STATE = 'RESET_REGISTER_STATE'
